### ISSUE TITLE
nrpe_exporter issue

### ISSUE THREAD

**Issue by jinoj** [canonical/nrpe_exporter#5]
[root@jino Downloads]# ./nrpe_exporter
level=info ts=2017-12-15T18:22:45.45790008Z caller=nrpe_exporter.go:129 msg="Starting nrpe_exporter" version="(version=, branch=, revision=)"
level=info ts=2017-12-15T18:22:45.457972373Z caller=nrpe_exporter.go:130 msg="Build context" build_context="(go=go1.9, user=, date=)"
level=info ts=2017-12-15T18:22:45.457995283Z caller=nrpe_exporter.go:131 msg="Listening on address" address=:9275
level=error ts=2017-12-15T18:22:49.152395908Z caller=nrpe_exporter.go:72 msg="Error running command" command=check_load err="read tcp 127.0.0.1:49300->127.0.0.1:5666: read: connection reset by peer"
^C

**Comment by brian-brazil** [comment]
It looks like that port isn't open.

**Comment by alexmnv** [comment]
I ran into the same problem. `nrpe_exporter` shows the following error:
`level=error ts=2018-01-09T06:18:29.957738088Z caller=nrpe_exporter.go:72 msg="Error running command" command=get_cpu_load err="read tcp 10.0.39.1:57981->10.0.39.50:5666: read: connection reset by peer"`

`/usr/lib/nagios/plugins/check_nrpe -H 10.0.39.50 -p 5666 -c get_cpu_load` works fine.
  
upd: The issue was that nrpe was using SSL which is not supported in `nrpe_exporter` unfortunately

**Comment by conr** [comment]
@alexmnv ~~SSL appears to be supported in this fork of the nrpe_exporter: https://github.com/criteo/nrpe_exporter which may be of use to you.~~
  
EDIT: Apologies, that fork does not actually support SSL.

**Comment by candlerb** [comment]
Yes, this is what you'll see when sending a non-SSL request to an nrpe server which is using SSL.  Duplicate of #4.
